---
abstract: 'argument validation for you'
author:
  - 'Tokuhiro Matsuno <tokuhirom  slkjfd gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  MooseX::Types: 0
  MouseX::Types: 0
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Smart-Args
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Exporter: 5.63
  Mouse: 0.92
  PadWalker: 1.92
  Scalar::Util: 1.21
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/p5-Smart-Args.git
version: 0.10
